### ISSUE TITLE
Création du scénario de l'introduction.

### ISSUE THREAD

**Issue by Sancho-Panza** [Sancho-Panza/Les-aventures-de-Papy#1]
Plop'

Du coup, @MrHibou, tu avais créé un texte pour l'intro, qui défilait façon StarWars, faudrait que tu le mettes ici et qu'on gère ça oklm. ;)

**Comment by MrHibou** [comment]
Oklm !

**Comment by Sancho-Panza** [comment]
Thx, c'est ici du coup: [Introduction](https://github.com/Sancho-Panza/Les-aventures-de-Papy/wiki/Introduction).
